# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  datapak_sys_config = debug
  datapak_config = debug
endif
ifeq ($(config),release)
  datapak_sys_config = release
  datapak_config = release
endif

PROJECTS := datapak-sys datapak

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

datapak-sys:
ifneq (,$(datapak_sys_config))
	@echo "==== Building datapak-sys ($(datapak_sys_config)) ===="
	@${MAKE} --no-print-directory -C . -f datapak-sys.make config=$(datapak_sys_config)
endif

datapak: datapak-sys
ifneq (,$(datapak_config))
	@echo "==== Building datapak ($(datapak_config)) ===="
	@${MAKE} --no-print-directory -C . -f datapak.make config=$(datapak_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f datapak-sys.make clean
	@${MAKE} --no-print-directory -C . -f datapak.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   datapak-sys"
	@echo "   datapak"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"